export const sagaActions = {
  FETCH_DATA: "FETCH_DATA",
  CREATE_USER_REQUESTED: "CREATE_USER_REQUESTED",
  DELETE_USER_REQUESTED: "DELETE_USER_REQUESTED",
  EDIT_USER_REQUESTED: "EDIT_USER_REQUESTED",
};
